services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: deadbook_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app_network
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - .:/code
    container_name: deadbook_api
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: deadbook_frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevent overwriting node_modules
    ports:
      - "5173:5173" # Vite's default dev server port
    networks:
      - app_network
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
